"""Constants for INKBIRD BBQ."""

DOMAIN = "inkbird_bbq"
MANUFACTURER = "INKBIRD"

CONF_MODEL = "model"

MODEL_ISC_027BW = "ISC-027BW"
MODEL_INT_14_BW = "INT-14-BW"
MODEL_TNT_11_B = "TNT-11-B"

SUPPORTED_MODELS = {
    MODEL_ISC_027BW,
    MODEL_INT_14_BW,
}

PLANNED_MODELS = {
    MODEL_TNT_11_B,
}

AUTO_DISCOVERY_NAMES = {
    MODEL_ISC_027BW: MODEL_ISC_027BW,
    MODEL_INT_14_BW: MODEL_INT_14_BW,
    "INT-14-BW_WH": MODEL_INT_14_BW,
}
