"""Constants for INKBIRD BBQ."""

DOMAIN = "inkbird_bbq"
MANUFACTURER = "INKBIRD"

MODEL_ISC_027BW = "ISC-027BW"
MODEL_INT_14_BW = "INT-14-BW"
MODEL_TNT_11_B = "TNT-11-B"

SUPPORTED_MODELS = {
    MODEL_ISC_027BW,
    MODEL_INT_14_BW,
    MODEL_TNT_11_B,
}
